# Common parameters
debug_level: 0

# Scan over all combinations of specified parameter values
parameter_scan:

  # pthat bins are required, and should come first
  pt_hat_bins:
    label: 'pt_hat_bins'
    spacing: '      '
    values: [5, 7, 10]

  # additional parameters are optional
  parameter1:
    label: 'vir_factor'
    spacing: '      '
    values: [0.25, 0.5]

# Generation
xml_user_file: '/home/jetscape-user/JETSCAPE/config/jetscape_user_PP19.xml'
xml_master_file: '/home/jetscape-user/JETSCAPE/config/jetscape_master.xml'
