# Common parameters
debug_level: 0
pt_hat_bins: [5, 7, 10, 15, 20, 25, 35, 45, 55, 65, 75, 85, 100, 125, 150, 180, 210, 250, 300, 500, 1000]

# Generation
xml_user_file: '/home/jetscape-user/JETSCAPE/config/jetscape_user_PP19.xml'
xml_master_file: '/home/jetscape-user/JETSCAPE/config/jetscape_master.xml'

# Analysis
jetR: [0.2, 0.4]
min_jet_pt: 20.
abs_jet_eta_max: 1.
n_event_max: 100

reader: hepmc

scale_histograms: False
merge_histograms: False
