# Common parameters
debug_level: 0
pt_hat_bins: [5, 7, 9, 12, 16, 21, 28, 36, 45, 57, 70, 85, 99, 115, 132, 150, 169, 190, 212, 235, 1000]

# Generation
xml_user_file: '/home/jetscape-user/JETSCAPE/config/jetscape_user_PP19.xml'
xml_master_file: '/home/jetscape-user/JETSCAPE/config/jetscape_master.xml'

# Analysis
jetR: [0.2, 0.4]
min_jet_pt: 20.
abs_jet_eta_max: 1.
n_event_max: 100

reader: hepmc                     # [hepmc, ascii]

scale_histograms: False
merge_histograms: False
