# Run parameters
pt_hat_bins: [5, 7, 9, 12, 16, 21, 28, 36, 45, 57, 70, 85, 99, 115, 132, 150, 169, 190, 212, 235, 1000]

output_dir: "/home/jetscape-user/JETSCAPE-output/PP19_2760_FullPtHat_colorless_test"

# Analysis parameters

# Plotting parameters
output_dir_pp: "/home/jetscape-user/JETSCAPE-output/PP19_2760_FullPtHat_colorless_test"
output_dir_AA: "/home/jetscape-user/JETSCAPE-output/MATTER+LBT_2760_FullPtHat"
nEvents_pp: 10000
nEvents_AA: 2500
file_format: ".pdf"
